services:
  web: # Go wallet service
    build: .
    container_name: go_wallet
    env_file:
      - config.env
    ports:
      - 8192:8192 # API port
    volumes:
      - .:/app
    depends_on:
      - db
    command: air cmd/main.go -b 0.0.0.0 # Run with live reload

  db: # PostgreSQL
    image: postgres:alpine
    container_name: go_db
    environment:
      - POSTGRES_USER=example_user
      - POSTGRES_PASSWORD=example_password
      - POSTGRES_DB=example_db
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data # Volume to persist DB Data between launches

volumes:
  postgres-db:
